// Centralized language catalog for translation options
// Each entry uses an ISO 639-1 code where available. Flags are best-effort; many use a generic globe.

export type Language = {
  code: string;
  name: string;
  flag: string; // emoji flag or globe
};

// ~160 languages (>= 150 requested). Codes are lowercased.
const LANG_SRC: Language[] = [
  // Most common (with flags)
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'pa', name: 'Punjabi', flag: '🇮🇳' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'jv', name: 'Javanese', flag: '🇮🇩' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'te', name: 'Telugu', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', flag: '🇵🇰' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'fa', name: 'Persian', flag: '🇮🇷' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'th', name: 'Thai', flag: '🇹🇭' },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱' },
  { code: 'el', name: 'Greek', flag: '🇬🇷' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴' },

  // Extended catalog (flags default to globe where ambiguous)
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', flag: '🌐' },
  { code: 'am', name: 'Amharic', flag: '🇪🇹' },
  { code: 'an', name: 'Aragonese', flag: '🇪🇸' },
  { code: 'as', name: 'Assamese', flag: '🇮🇳' },
  { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'be', name: 'Belarusian', flag: '🇧🇾' },
  { code: 'bg', name: 'Bulgarian', flag: '🇧🇬' },
  { code: 'bh', name: 'Bihari', flag: '🌐' },
  { code: 'bi', name: 'Bislama', flag: '🇻🇺' },
  { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
  { code: 'ca', name: 'Catalan', flag: '🇪🇸' },
  { code: 'ce', name: 'Chechen', flag: '🇷🇺' },
  { code: 'co', name: 'Corsican', flag: '🇫🇷' },
  { code: 'cs', name: 'Czech', flag: '🇨🇿' },
  { code: 'cy', name: 'Welsh', flag: '🏴' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'dv', name: 'Divehi', flag: '🇲🇻' },
  { code: 'dz', name: 'Dzongkha', flag: '🇧🇹' },
  { code: 'ee', name: 'Ewe', flag: '🇬🇭' },
  { code: 'eo', name: 'Esperanto', flag: '🌐' },
  { code: 'et', name: 'Estonian', flag: '🇪🇪' },
  { code: 'eu', name: 'Basque', flag: '🇪🇸' },
  { code: 'ff', name: 'Fulah', flag: '🌐' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'fj', name: 'Fijian', flag: '🇫🇯' },
  { code: 'fo', name: 'Faroese', flag: '🇫🇴' },
  { code: 'fy', name: 'Western Frisian', flag: '🇳🇱' },
  { code: 'ga', name: 'Irish', flag: '🇮🇪' },
  { code: 'gd', name: 'Scottish Gaelic', flag: '🏴' },
  { code: 'gl', name: 'Galician', flag: '🇪🇸' },
  { code: 'gn', name: 'Guarani', flag: '🇵🇾' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { code: 'haw', name: 'Hawaiian', flag: '🇺🇸' },
  { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
  { code: 'ht', name: 'Haitian Creole', flag: '🇭🇹' },
  { code: 'hu', name: 'Hungarian', flag: '🇭🇺' },
  { code: 'hy', name: 'Armenian', flag: '🇦🇲' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
  { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
  { code: 'iu', name: 'Inuktitut', flag: '🇨🇦' },
  { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
  { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
  { code: 'km', name: 'Khmer', flag: '🇰🇭' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ks', name: 'Kashmiri', flag: '🇮🇳' },
  { code: 'ku', name: 'Kurdish', flag: '🌐' },
  { code: 'ky', name: 'Kyrgyz', flag: '🇰🇬' },
  { code: 'la', name: 'Latin', flag: '🌐' },
  { code: 'lb', name: 'Luxembourgish', flag: '🇱🇺' },
  { code: 'lg', name: 'Ganda', flag: '🇺🇬' },
  { code: 'ln', name: 'Lingala', flag: '🇨🇩' },
  { code: 'lo', name: 'Lao', flag: '🇱🇦' },
  { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
  { code: 'lv', name: 'Latvian', flag: '🇱🇻' },
  { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
  { code: 'mi', name: 'Māori', flag: '🇳🇿' },
  { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
  { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
  { code: 'mo', name: 'Moldavian', flag: '🇲🇩' },
  { code: 'ms', name: 'Malay', flag: '🇲🇾' },
  { code: 'mt', name: 'Maltese', flag: '🇲🇹' },
  { code: 'my', name: 'Burmese', flag: '🇲🇲' },
  { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'nn', name: 'Norwegian Nynorsk', flag: '🇳🇴' },
  { code: 'nb', name: 'Norwegian Bokmål', flag: '🇳🇴' },
  { code: 'ny', name: 'Chichewa', flag: '🇲🇼' },
  { code: 'oc', name: 'Occitan', flag: '🇫🇷' },
  { code: 'om', name: 'Oromo', flag: '🇪🇹' },
  { code: 'or', name: 'Odia', flag: '🇮🇳' },
  { code: 'os', name: 'Ossetian', flag: '🇷🇺' },
  { code: 'ps', name: 'Pashto', flag: '🇦🇫' },
  { code: 'qu', name: 'Quechua', flag: '🇵🇪' },
  { code: 'rm', name: 'Romansh', flag: '🇨🇭' },
  { code: 'rn', name: 'Rundi', flag: '🇧🇮' },
  { code: 'sa', name: 'Sanskrit', flag: '🇮🇳' },
  { code: 'sc', name: 'Sardinian', flag: '🇮🇹' },
  { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
  { code: 'si', name: 'Sinhala', flag: '🇱🇰' },
  { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovene', flag: '🇸🇮' },
  { code: 'sm', name: 'Samoan', flag: '🇼🇸' },
  { code: 'sn', name: 'Shona', flag: '🇿🇼' },
  { code: 'so', name: 'Somali', flag: '🇸🇴' },
  { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
  { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
  { code: 'ss', name: 'Swati', flag: '🇸🇿' },
  { code: 'st', name: 'Southern Sotho', flag: '🇱🇸' },
  { code: 'su', name: 'Sundanese', flag: '🇮🇩' },
  { code: 'sw', name: 'Swahili', flag: '🇰🇪' },
  { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
  { code: 'ti', name: 'Tigrinya', flag: '🇪🇷' },
  { code: 'tk', name: 'Turkmen', flag: '🇹🇲' },
  { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'tn', name: 'Tswana', flag: '🇧🇼' },
  { code: 'to', name: 'Tongan', flag: '🇹🇴' },
  { code: 'ts', name: 'Tsonga', flag: '🇿🇦' },
  { code: 'tt', name: 'Tatar', flag: '🇷🇺' },
  { code: 'tw', name: 'Twi', flag: '🇬🇭' },
  { code: 'ug', name: 'Uyghur', flag: '🇨🇳' },
  { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
  { code: 've', name: 'Venda', flag: '🇿🇦' },
  { code: 'wa', name: 'Walloon', flag: '🇧🇪' },
  { code: 'xh', name: 'Xhosa', flag: '🇿🇦' },
  { code: 'yi', name: 'Yiddish', flag: '🌐' },
  { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', flag: '🇿🇦' },
  { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
  { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
  { code: 'ht', name: 'Haitian Creole', flag: '🇭🇹' },
  { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
  { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
  { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
  { code: 'ky', name: 'Kyrgyz', flag: '🇰🇬' },
  { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
  { code: 'tk', name: 'Turkmen', flag: '🇹🇲' },

  // Additional widely-used languages
  { code: 'ro', name: 'Romanian', flag: '🇷🇴' },
  { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovene', flag: '🇸🇮' },
  { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
  { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
  { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
  { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
  { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
  { code: 'lv', name: 'Latvian', flag: '🇱🇻' },
  { code: 'et', name: 'Estonian', flag: '🇪🇪' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
  { code: 'ga', name: 'Irish', flag: '🇮🇪' },
  { code: 'gd', name: 'Scottish Gaelic', flag: '🏴' },
  { code: 'cy', name: 'Welsh', flag: '🏴' },
  { code: 'mt', name: 'Maltese', flag: '🇲🇹' },

  // African languages
  { code: 'sw', name: 'Swahili', flag: '🇰🇪' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
  { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { code: 'am', name: 'Amharic', flag: '🇪🇹' },
  { code: 'ti', name: 'Tigrinya', flag: '🇪🇷' },
  { code: 'so', name: 'Somali', flag: '🇸🇴' },
  { code: 'rw', name: 'Kinyarwanda', flag: '🇷🇼' },
  { code: 'lg', name: 'Ganda', flag: '🇺🇬' },
  { code: 'sn', name: 'Shona', flag: '🇿🇼' },
  { code: 'st', name: 'Southern Sotho', flag: '🇱🇸' },
  { code: 'tn', name: 'Tswana', flag: '🇧🇼' },
  { code: 'xh', name: 'Xhosa', flag: '🇿🇦' },
  { code: 'zu', name: 'Zulu', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', flag: '🇬🇭' },

  // Additional Indo-Aryan/Dravidian/SE Asia
  { code: 'as', name: 'Assamese', flag: '🇮🇳' },
  { code: 'bh', name: 'Bihari', flag: '🌐' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
  { code: 'or', name: 'Odia', flag: '🇮🇳' },
  { code: 'si', name: 'Sinhala', flag: '🇱🇰' },
  { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
  { code: 'km', name: 'Khmer', flag: '🇰🇭' },
  { code: 'my', name: 'Burmese', flag: '🇲🇲' },
  { code: 'lo', name: 'Lao', flag: '🇱🇦' },
  { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
  { code: 'ka', name: 'Georgian', flag: '🇬🇪' },

  // Pacific
  { code: 'mi', name: 'Māori', flag: '🇳🇿' },
  { code: 'sm', name: 'Samoan', flag: '🇼🇸' },
  { code: 'fj', name: 'Fijian', flag: '🇫🇯' },
  { code: 'to', name: 'Tongan', flag: '🇹🇴' },

  // Americas
  { code: 'qu', name: 'Quechua', flag: '🇵🇪' },
  { code: 'gn', name: 'Guarani', flag: '🇵🇾' },
  { code: 'ay', name: 'Aymara', flag: '🇧🇴' },
  { code: 'br', name: 'Breton', flag: '🇫🇷' },
  { code: 'bm', name: 'Bambara', flag: '🇲🇱' },
  { code: 'bo', name: 'Tibetan', flag: '🇨🇳' },
  { code: 'ckb', name: 'Central Kurdish', flag: '🇮🇶' },
  { code: 'ug', name: 'Uyghur', flag: '🇨🇳' },
  { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
  { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },

  // Missing ISO 639-1 codes to push over 150 unique
  { code: 'aa', name: 'Afar', flag: '🌐' },
  { code: 'ab', name: 'Abkhaz', flag: '🌐' },
  { code: 'ae', name: 'Avestan', flag: '🌐' },
  { code: 'av', name: 'Avaric', flag: '🌐' },
  { code: 'ba', name: 'Bashkir', flag: '🌐' },
  { code: 'ch', name: 'Chamorro', flag: '🇬🇺' },
  { code: 'cr', name: 'Cree', flag: '🇨🇦' },
  { code: 'cu', name: 'Church Slavic', flag: '🌐' },
  { code: 'cv', name: 'Chuvash', flag: '🌐' },
  { code: 'gv', name: 'Manx', flag: '🇮🇲' },
  { code: 'ik', name: 'Inupiaq', flag: '🇺🇸' },
  { code: 'io', name: 'Ido', flag: '🌐' },
  { code: 'ii', name: 'Sichuan Yi', flag: '🇨🇳' },
  { code: 'ki', name: 'Kikuyu', flag: '🇰🇪' },
  { code: 'kj', name: 'Kuanyama', flag: '🌐' },
  { code: 'kv', name: 'Komi', flag: '🇷🇺' },
  { code: 'li', name: 'Limburgish', flag: '🇳🇱' },
  { code: 'mh', name: 'Marshallese', flag: '🇲🇭' },
  { code: 'na', name: 'Nauru', flag: '🇳🇷' },
  { code: 'nd', name: 'North Ndebele', flag: '🇿🇼' },
  { code: 'nr', name: 'South Ndebele', flag: '🇿🇦' },
  { code: 'ng', name: 'Ndonga', flag: '🇳🇦' },
  { code: 'nv', name: 'Navajo', flag: '🇺🇸' },
  { code: 'oj', name: 'Ojibwa', flag: '🇨🇦' },
  { code: 'pi', name: 'Pali', flag: '🌐' },
  { code: 'se', name: 'Northern Sami', flag: '🇳🇴' },
  { code: 'sg', name: 'Sango', flag: '🇨🇫' },
  { code: 'vo', name: 'Volapük', flag: '🌐' },
  { code: 'za', name: 'Zhuang', flag: '🇨🇳' },
  { code: 'kl', name: 'Kalaallisut', flag: '🇬🇱' },
  { code: 'kw', name: 'Cornish', flag: '🏴' },
  { code: 'wo', name: 'Wolof', flag: '🇸🇳' },
  { code: 'ia', name: 'Interlingua', flag: '🌐' },
  { code: 'ie', name: 'Interlingue', flag: '🌐' },
];

// Deduplicate by code while preserving last occurrence
export const LANGUAGES: Language[] = Object.values(
  LANG_SRC.reduce((acc, l) => {
    acc[l.code] = l;
    return acc;
  }, {} as Record<string, Language>)
).sort((a, b) => a.name.localeCompare(b.name));

// Build a name map for prompt friendliness
export const LANG_NAME_MAP: Record<string, string> = LANGUAGES.reduce((acc, { code, name }) => {
  acc[code.toLowerCase()] = name;
  return acc;
}, {} as Record<string, string>);

export const getLanguageName = (code: string): string => {
  return LANG_NAME_MAP[code?.toLowerCase?.() || ''] || code;
};

// Convenience export: only languages that have a non-generic flag (exclude globe)
export const LANGUAGES_WITH_FLAGS: Language[] = LANGUAGES.filter(l => l.flag && l.flag !== '🌐');
